In [1]:
!pip install matplotlib pandas seaborn numpy nltk

Requirement already satisfied: matplotlib in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (3.8.0)
Requirement already satisfied: pandas in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (2.1.1)
Requirement already satisfied: seaborn in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (0.13.0)
Requirement already satisfied: numpy in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (1.26.1)
Requirement already satisfied: nltk in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (3.8.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: click in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from nltk) (4.66.1)
Requirement already satisfied: six>=1.5 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: colorama in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from click->nltk) (0.4.6)

In [2]:
%matplotlib inline

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import _pickle as cPickle
import nltk

In [3]:
df = pd.read_csv('lsapp.tsv', sep='\t', skiprows=1, header=None, names=['user_id', 'session_id', 'timestamp', 'app_name', 'event_type'])
df_open = df.loc[df['event_type'] == 'Opened']

In [4]:
df

,user_id,session_id,timestamp,app_name,event_type
0,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Closed
2,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Opened
3,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Closed
4,0,1,2018-01-16 06:01:08,Minesweeper Classic (Mines),Opened
...,...,...,...,...,...
3658584,291,76247,2018-04-06 14:35:15,Facebook,Closed
3658585,291,76247,2018-04-06 14:35:15,Facebook,Opened
3658586,291,76247,2018-04-06 14:35:37,Facebook,Closed
3658587,291,76247,2018-04-06 14:35:37,Facebook,Opened
3658588,291,76247,2018-04-06 14:35:52,Facebook Messenger,User Interaction

In [5]:
df_open.loc[:,'timestamp'] = pd.to_datetime(df_open['timestamp'])
df.loc[:,'timestamp'] = pd.to_datetime(df['timestamp'])

In [6]:
df = df.iloc[:-1, :] # last row includes only NaNs and NaT (not a number)
df

,user_id,session_id,timestamp,app_name,event_type
0,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Closed
2,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Opened
3,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Closed
4,0,1,2018-01-16 06:01:08,Minesweeper Classic (Mines),Opened
...,...,...,...,...,...
3658583,291,76247,2018-04-06 14:34:34,Facebook,Opened
3658584,291,76247,2018-04-06 14:35:15,Facebook,Closed
3658585,291,76247,2018-04-06 14:35:15,Facebook,Opened
3658586,291,76247,2018-04-06 14:35:37,Facebook,Closed
3658587,291,76247,2018-04-06 14:35:37,Facebook,Opened

In [7]:
df['time_dff']  = df[['timestamp']].diff()
df['interaction_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(1, 'm')) 
                              & (df.event_type == 'Opened')) 
                              | ~(df.app_name == df.app_name.shift(1))
                              | ~(df.user_id == df.user_id.shift(1))).cumsum()
df['session_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(5, 'm')) 
                              & (df.event_type == 'Opened')) 
                              | ~(df.user_id == df.user_id.shift(1))).cumsum()
df_start = df.drop_duplicates(subset=['interaction_id'], keep='first')
df_end = df.drop_duplicates(subset=['interaction_id'], keep='last')
df_start.set_index('interaction_id', inplace=True)
df_end.set_index('interaction_id', inplace=True)
df_start.loc[:, 'open_time'] = df_start['timestamp']
df_start.loc[:, 'close_time']  = df_end['timestamp']

C:\Users\Brin\AppData\Local\Temp\ipykernel_17340\4188201099.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time_dff']  = df[['timestamp']].diff()
C:\Users\Brin\AppData\Local\Temp\ipykernel_17340\4188201099.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['interaction_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(1, 'm'))
C:\Users\Brin\AppData\Local\Temp\ipykernel_17340\4188201099.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['session_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(5, 'm'))
C:\Users\Brin\AppData\Local\Temp\ipykernel_17340\4188201099.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start.loc[:, 'open_time'] = df_start['timestamp']
C:\Users\Brin\AppData\Local\Temp\ipykernel_17340\4188201099.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start.loc[:, 'close_time']  = df_end['timestamp']

In [15]:
df_start.head(20)

,user_id,session_id,timestamp,app_name,event_type,time_dff,open_time,close_time
interaction_id,,,,,,,,
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened,NaN,2018-01-16 06:01:05,2018-01-16 06:01:09
2,0,1,2018-01-16 06:03:44,Minesweeper Classic (Mines),Opened,0 days 00:02:35,2018-01-16 06:03:44,2018-01-16 06:04:17
3,0,1,2018-01-16 06:25:54,Gmail,User Interaction,0 days 00:21:37,2018-01-16 06:25:54,2018-01-16 06:25:54
4,0,1,2018-01-16 06:26:05,Google,Opened,0 days 00:00:11,2018-01-16 06:26:05,2018-01-16 06:26:10
5,0,1,2018-01-16 06:26:10,Instagram,Opened,0 days 00:00:00,2018-01-16 06:26:10,2018-01-16 06:26:21
6,0,1,2018-01-16 06:26:21,Google,Opened,0 days 00:00:00,2018-01-16 06:26:21,2018-01-16 06:26:26
7,0,1,2018-01-16 06:26:26,Google Chrome,Opened,0 days 00:00:00,2018-01-16 06:26:26,2018-01-16 06:36:26
8,0,2,2018-01-16 07:15:56,Minesweeper Classic (Mines),Opened,0 days 00:39:30,2018-01-16 07:15:56,2018-01-16 07:15:58
9,0,2,2018-01-16 07:20:45,Google Chrome,Opened,0 days 00:04:47,2018-01-16 07:20:45,2018-01-16 07:20:45
10,0,2,2018-01-16 07:20:46,Minesweeper Classic (Mines),Opened,0 days 00:00:01,2018-01-16 07:20:46,2018-01-16 07:21:43
11,0,2,2018-01-16 07:21:44,Google Chrome,Opened,0 days 00:00:01,2018-01-16 07:21:44,2018-01-16 07:21:44
12,0,3,2018-01-16 08:02:05,Minesweeper Classic (Mines),Opened,0 days 00:40:21,2018-01-16 08:02:05,2018-01-16 08:02:05
13,0,3,2018-01-16 08:03:34,Google Chrome,Opened,0 days 00:01:29,2018-01-16 08:03:34,2018-01-16 08:03:34
14,0,3,2018-01-16 08:03:34,Minesweeper Classic (Mines),Opened,0 days 00:00:00,2018-01-16 08:03:34,2018-01-16 08:04:10
15,0,3,2018-01-16 08:04:11,Google Chrome,Opened,0 days 00:00:01,2018-01-16 08:04:11,2018-01-16 08:04:11
16,0,4,2018-01-16 08:30:44,Minesweeper Classic (Mines),Opened,0 days 00:26:33,2018-01-16 08:30:44,2018-01-16 08:30:44
17,0,4,2018-01-16 08:31:50,Google Chrome,Opened,0 days 00:01:06,2018-01-16 08:31:50,2018-01-16 08:31:50
18,0,4,2018-01-16 08:31:51,Minesweeper Classic (Mines),Opened,0 days 00:00:01,2018-01-16 08:31:51,2018-01-16 08:34:13
19,0,4,2018-01-16 08:34:14,Google Chrome,Opened,0 days 00:00:01,2018-01-16 08:34:14,2018-01-16 08:34:14
20,0,5,2018-01-16 09:45:51,Minesweeper Classic (Mines),Opened,0 days 01:11:37,2018-01-16 09:45:51,2018-01-16 09:45:51

## Session time

### Sum of interaction times

In [9]:
# session time is sum of all interactions
df_start.groupby('session_id')['time_dff'].sum()

session_id
1        0 days 00:24:23
2        0 days 00:44:19
3        0 days 00:41:51
4        0 days 00:27:41
5        0 days 01:25:01
              ...
33216    0 days 00:38:56
33217    0 days 03:50:05
33218    0 days 00:17:11
33219    0 days 00:26:59
33220    0 days 01:14:18
Name: time_dff, Length: 33220, dtype: object

### Time difference between first and last session interaction

In [18]:
# session time as difference between first session usage open_time and last session usage close_time
df_session_time = df_start.groupby('session_id').apply(lambda x: x['close_time'].max() - x['open_time'].min())
df_session_time.head(50)

session_id
1    0 days 00:35:21
2    0 days 00:05:48
3    0 days 00:02:06
4    0 days 00:03:30
5    0 days 00:44:03
6    0 days 00:01:59
7    0 days 00:00:32
8    0 days 00:00:15
9    0 days 00:07:52
10   0 days 00:00:52
11   0 days 00:02:09
12   0 days 00:08:40
13   0 days 00:00:28
14   0 days 00:43:05
15   0 days 00:00:30
16   0 days 00:04:49
17   0 days 00:03:15
18   0 days 00:01:49
19   0 days 00:01:10
20   0 days 00:05:46
21   0 days 00:03:47
22   0 days 00:00:45
23   0 days 01:17:13
24   0 days 00:00:07
25   0 days 00:00:02
26   0 days 00:00:00
27   0 days 00:00:26
28   0 days 00:00:00
29   0 days 00:00:01
30   0 days 00:00:00
31   1 days 14:49:19
32   0 days 00:00:54
33   0 days 01:44:17
34   0 days 00:00:09
35   0 days 00:00:01
36   0 days 01:33:08
37   0 days 00:00:02
38   0 days 00:00:18
39   0 days 00:15:54
40   0 days 00:00:22
41   0 days 00:02:10
42   0 days 00:02:36
43   0 days 00:03:00
44   0 days 00:11:16
45   0 days 01:07:23
46   0 days 00:22:45
47   0 days 00:08:13
48   0 days 00:09:14
49   0 days 00:00:22
50   0 days 00:02:49
dtype: timedelta64[ns]

In [16]:
# Compute mean and standard deviation of session times
mean_session_time = df_session_time.mean()
std_session_time = df_session_time.std()

mean_session_time, std_session_time

(Timedelta('0 days 01:21:17.672877784'),
 Timedelta('0 days 16:01:32.896302107'))

## Prediction

### Setup

In [25]:
# print number of users by counting unique user ids
df_start['user_id'].nunique()

292

In [21]:
# for each user create its own dataframe
df_user = df_start.groupby('user_id')

In [24]:
# print 10 rows of first user
df_user.get_group(0).head(10)

,user_id,session_id,timestamp,app_name,event_type,time_dff,open_time,close_time
interaction_id,,,,,,,,
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened,NaN,2018-01-16 06:01:05,2018-01-16 06:01:09
2,0,1,2018-01-16 06:03:44,Minesweeper Classic (Mines),Opened,0 days 00:02:35,2018-01-16 06:03:44,2018-01-16 06:04:17
3,0,1,2018-01-16 06:25:54,Gmail,User Interaction,0 days 00:21:37,2018-01-16 06:25:54,2018-01-16 06:25:54
4,0,1,2018-01-16 06:26:05,Google,Opened,0 days 00:00:11,2018-01-16 06:26:05,2018-01-16 06:26:10
5,0,1,2018-01-16 06:26:10,Instagram,Opened,0 days 00:00:00,2018-01-16 06:26:10,2018-01-16 06:26:21
6,0,1,2018-01-16 06:26:21,Google,Opened,0 days 00:00:00,2018-01-16 06:26:21,2018-01-16 06:26:26
7,0,1,2018-01-16 06:26:26,Google Chrome,Opened,0 days 00:00:00,2018-01-16 06:26:26,2018-01-16 06:36:26
8,0,2,2018-01-16 07:15:56,Minesweeper Classic (Mines),Opened,0 days 00:39:30,2018-01-16 07:15:56,2018-01-16 07:15:58
9,0,2,2018-01-16 07:20:45,Google Chrome,Opened,0 days 00:04:47,2018-01-16 07:20:45,2018-01-16 07:20:45
10,0,2,2018-01-16 07:20:46,Minesweeper Classic (Mines),Opened,0 days 00:00:01,2018-01-16 07:20:46,2018-01-16 07:21:43

In [27]:
# for user 0 print all unique app names
df_user.get_group(0)['app_name'].unique()

array(['Minesweeper Classic (Mines)', 'Gmail', 'Google', 'Instagram',
       'Google Chrome', 'Clock', 'Maps', 'YouTube', 'Facebook',
       'Messages', 'Phone', 'Snapchat', 'Settings', 'Google Photos',
       'Hangouts', 'Amazon Shopping', 'Facebook Messenger',
       'Google Play Store', 'Calendar'], dtype=object)

### Random app

In [38]:
# create user to app dictionary including all unique app names for each user
user_to_app_dict = {}

for user_id, user_df in df_user:
    user_to_app_dict[user_id] = user_df['app_name'].unique()

# print user to app dictionary
user_to_app_dict

{0: array(['Minesweeper Classic (Mines)', 'Gmail', 'Google', 'Instagram',
        'Google Chrome', 'Clock', 'Maps', 'YouTube', 'Facebook',
        'Messages', 'Phone', 'Snapchat', 'Settings', 'Google Photos',
        'Hangouts', 'Amazon Shopping', 'Facebook Messenger',
        'Google Play Store', 'Calendar'], dtype=object),
 1: array(['Google Photos', 'Discord', 'Messages', 'Google', 'Snapchat',
        'Instagram', 'Google Chrome', 'Facebook Messenger', 'Facebook',
        'Google Drive', 'Twitter', 'Google Play Store', 'YouTube', 'Phone',
        'Spotify Music', 'Clock', 'Settings', 'Reddit'], dtype=object),
 2: array(['Android In Call UI', 'Receipt Hog', 'Gmail', 'Facebook',
        'Google Chrome', 'Instagram', 'Amazon Shopping', 'Google',
        'Snapchat', 'Maps', 'Ibotta', 'YouTube', 'Spotify Music',
        'Google Play Store', 'Settings', 'Facebook Messenger'],
       dtype=object),
 3: array(['PayPal Mobile Cash', 'Google Play Store', 'Google Chrome',
        'YouTube', 'Android In Call UI', 'Contacts', 'Samsung Notes',
        'Messaging', 'Settings', 'Gmail', 'Samsung Gallery', 'eBay',
        'Flipboard Briefing', 'Camera', 'Maps'], dtype=object),
 4: array(['Android In Call UI', 'Yahoo Mail', 'Google Chrome', 'Maps',
        'Google Play Store', 'Settings', 'Discord', 'Contacts'],
       dtype=object),
 5: array(['S’more', 'Twitter', 'Instagram', 'Google Chrome', 'Facebook',
        'YouTube', 'Snapchat', 'Gmail', 'Flipboard Briefing', 'Lucktastic',
        'Samsung Notes', 'Contacts', 'Pinterest', 'Google Play Store',
        'Settings', 'Facebook Messenger', 'Samsung Gallery', 'Messages',
        'Camera', 'Words With Friends 2', 'Google Drive',
        'Google Play Music', 'Calculator', 'Google', 'Spotify Music',
        'Samsung Internet Browser', 'Hulu', 'Discord', 'Maps',
        'Google Photos', 'Walmart', 'Calendar'], dtype=object),
 6: array(['Google', 'Snapchat', 'Samsung Internet Browser', 'Gmail',
        'Words With Friends 2', 'Reddit', 'Google Play Store', 'Maps',
        'Contacts', 'Calendar', 'Calculator', 'Google Drive',
        'PayPal Mobile Cash', 'MUIQ Survey App', 'Settings', 'Camera',
        'YouTube', 'Amazon Shopping', 'Google Chrome',
        'Facebook Messenger', 'Samsung Gallery', 'Facebook', 'Messages'],
       dtype=object),
 7: array(['Facebook Messenger', 'YouTube', 'Google', 'Google Chrome',
        'Camera', 'Messages', 'Settings', 'Google Play Store', 'Facebook',
        'Samsung Internet Browser', 'Google Play Music', 'Calendar',
        'Gmail', 'Pinterest', 'Contacts', 'Maps', 'Google Drive',
        'Snapchat', 'Google Photos', 'Samsung Gallery', 'Calculator',
        'Amazon Shopping'], dtype=object),
 8: array(['Words With Friends 2', 'WhatsApp Messenger', 'Google Chrome',
        'Google Play Store', 'Settings', 'Calendar', 'YouTube',
        'Google Play Music', 'Google', 'Phone', 'Twitter'], dtype=object),
 9: array(['Google', 'Maps', 'Gmail', 'Google Chrome', 'Samsung Gallery',
        'Calendar', 'eBay', 'Google Drive', 'Messages', 'Settings',
        'Google Play Store', 'YouTube', 'Robinhood', 'Calorie Counter',
        'Camera', 'Calculator', 'Amazon Shopping', 'Pandora Music',
        'Contacts', 'Google Photos'], dtype=object),
 10: array(['Google Play Store', 'Settings', 'Google Chrome', 'Google',
        'Microsoft Outlook', 'Maps', 'Gmail'], dtype=object),
 11: array(['Samsung Internet Browser', 'Samsung Email', 'Maps', 'Camera',
        'Contacts', 'Settings', 'Messages', 'Calculator',
        'Google Play Store', 'Google Play Music', 'Google',
        'Samsung Gallery', 'YouTube', 'Calendar', 'MUIQ Survey App',
        'Walmart', 'Google Chrome'], dtype=object),
 12: array(['Google Drive', 'Contacts', 'Messages', 'Facebook Messenger',
        'Settings', 'Instagram', 'Google Photos', 'Google', 'Gmail',
        'Facebook', 'YouTube', 'Flipboard Briefing', 'Samsung Notes',
        'Samsung Gallery', 'Camera', 'WhatsApp Messenger', 'Calendar',
        'Google Chrome', 'Google Play Store', 'Maps'], dtype=object),
 13: array(['Facebook Messenger', 'Facebook', 'Messages', 'Contacts',
        'Calculator', 'Camera', 'Samsung Gallery',
        'Samsung Internet Browser', 'Instagram', 'Yahoo Mail', 'Pinterest',
        'Amazon Shopping', 'Snapchat', 'Netflix', 'Google Chrome',
        'Walmart', 'Settings', 'Google Play Store', 'YouTube',
        'Google Photos'], dtype=object),
 14: array(['Google Chrome', 'YouTube', 'Google Play Store', 'Google',
        'Settings', 'Camera', 'Samsung Gallery', 'Contacts'], dtype=object),
 15: array(['YouTube', 'Settings', 'Google Play Store', 'Android In Call UI',
        'Microsoft Outlook', 'Gmail', 'Messenger Lite', 'Google',
        'Google Chrome', 'Messages', 'Lucktastic', 'Contacts',
        'Yahoo Mail', 'Maps', 'Reward Stash', 'Facebook', 'Google Drive',
        'OfferUp', 'Brave Browser'], dtype=object),
 16: array(['Messages', 'Slidejoy', 'Gmail', 'Twitter', 'Google Chrome',
        'Contacts', 'Camera', 'Samsung Gallery', 'Facebook Messenger',
        'Facebook', 'Google', 'Settings', 'Google Play Store',
        'Lucktastic', 'Calculator', 'Robinhood', 'Instagram', 'Maps',
        'Ibotta', 'Amazon Shopping'], dtype=object),
 17: array(['Discord', 'Messages', 'Gmail', 'Contacts', 'Facebook', 'Settings',
        'Samsung Internet Browser', 'Samsung Gallery', 'Maps',
        'Google Photos', 'Camera', 'YouTube', 'Google Play Store',
        'Google'], dtype=object),
 18: array(['Facebook', 'Yahoo Mail', 'Google Photos', 'Settings',
        'Google Chrome', 'Verizon Messages', 'Gmail', 'Instagram',
        'Google', 'Phone', 'Amazon Shopping', 'Google Play Store',
        'Facebook Messenger', 'Clock', 'Messages', 'YouTube', 'Maps',
        'MUIQ Survey App', 'Google Drive', 'Google Play Music',
        'Pinterest'], dtype=object),
 19: array(['Messages', 'Facebook', 'Gmail', 'Pinterest', 'Google Play Store',
        'Facebook Messenger', 'YouTube', 'Snapchat', 'Contacts',
        'Amazon Shopping', 'Google Chrome', 'Settings', 'Calculator',
        'Spotify Music', 'Instagram', 'Maps', 'Netflix'], dtype=object),
 20: array(['Calculator', 'Gmail', 'YouTube', 'Camera', 'Google',
        'Samsung Notes', 'Google Chrome', 'Samsung Gallery',
        'Google Play Store', 'Settings', 'Google Photos'], dtype=object),
 21: array(['Contacts', 'Settings', 'Flipboard Briefing', 'Discord', 'YouTube',
        'Samsung Email', 'Google Photos', 'Google Chrome', 'Gmail',
        'Facebook', 'Google Play Store', 'Samsung Notes', 'Google Drive',
        'Camera', 'Facebook Messenger', 'Messages', 'Maps',
        'Google Play Music', 'Calculator'], dtype=object),
 22: array(['Facebook', 'Samsung Pay', 'Google', 'Google Chrome', 'Walmart',
        'Pandora Music', 'Google Play Store', 'Contacts', 'Messages',
        'Yahoo Mail', 'Samsung Email', 'Gmail', 'Samsung Internet Browser',
        'Settings', 'Maps', 'Instagram', 'Camera', 'OfferUp',
        'Facebook Messenger', 'Snapchat', 'Lucktastic', 'YouTube',
        'Amazon Shopping', 'Spotify Music', 'Calendar', 'Calculator',
        'TextNow'], dtype=object),
 23: array(['Samsung Email', 'Messages', 'Facebook', 'Twitter',
        'Samsung Internet Browser', 'Facebook Messenger', 'Contacts',
        'Calendar', 'Google', 'Amazon Shopping', 'Google Play Store',
        'Settings', 'Google Chrome', 'eBay'], dtype=object),
 24: array(['Google Chrome', 'YouTube', 'Google', 'Google Drive', 'Calendar',
        'Google Play Store', 'Settings', 'Gmail'], dtype=object),
 25: array(['Instagram', 'Reddit', 'Google', 'Facebook Messenger',
        'Google Chrome', 'Snapchat', 'Gmail', 'Google Photos', 'eBay',
        'YouTube', 'Messages', 'Amazon Shopping', 'Clock', 'Spotify Music',
        'Twitter', 'Netflix', 'Google Play Store', 'Settings',
        'Google Drive', 'Phone', 'Ibotta', 'Walmart'], dtype=object),
 26: array(['Android In Call UI', 'YouTube', 'Contacts', 'WhatsApp Messenger',
        'Settings', 'Google Chrome', 'Maps', 'Microsoft Outlook', 'Gmail',
        'Messaging', 'Google Play Store', 'Facebook', 'Google Photos',
        'Amazon Shopping', 'Google', 'Facebook Messenger', 'Hangouts'],
       dtype=object),
 27: array(['YouTube', 'Gmail', 'Google Chrome', 'Google Play Store',
        'Google Photos', 'Phone', 'Settings', 'Google Drive', 'Discord',
        'Google'], dtype=object),
 28: array(['Facebook', 'Facebook Messenger', 'Maps', 'Google Chrome', 'Gmail',
        'WhatsApp Messenger', 'Settings', 'Google Drive', 'Google',
        'Google Photos', 'Phone', 'Clock', 'Messages', 'Google Play Store',
        'Hulu'], dtype=object),
 29: array(['Google Chrome', 'Facebook Messenger', 'Messages',
        'Messenger Lite', 'Gmail', 'Phone', 'Contacts', 'Settings',
        'Calendar', 'Google Play Store', 'Instagram'], dtype=object),
 30: array(['Google', 'Contacts', 'Samsung Gallery', 'Maps', 'Google Chrome',
        'Google Play Store', 'Settings', 'YouTube', 'Calculator', 'imo',
        'Messages', 'Snapchat', 'WhatsApp Messenger', 'Camera',
        'Swagbucks', 'Calendar'], dtype=object),
 31: array(['Telegram', 'Settings', 'Google Chrome', 'Maps', 'Google',
        'Clean Master', 'Google Play Store', 'YouTube', 'Google Drive',
        'Gmail', 'WhatsApp Messenger'], dtype=object),
 32: array(['Gmail', 'Google', 'Facebook', 'Google Chrome',
        'Google Play Store', 'Clock', 'Facebook Messenger',
        'Google Photos', 'Settings'], dtype=object),
 33: array(['Contacts', 'Messaging', 'Podcast Addict', 'Samsung Email',
        'Samsung Internet Browser', 'The PCH App', 'Robinhood',
        'Android In Call UI', 'YouTube', 'Settings', 'Google Play Store',
        'Maps', 'Samsung Gallery', 'Walmart', 'Camera', 'Calculator',
        'Google Drive'], dtype=object),
 34: array(['Facebook', 'Gmail', 'Google Drive', 'Facebook Messenger',
        'Google Chrome', 'YouTube', 'Phone', 'Android In Call UI',
        'Google Play Store', 'Settings', 'Walmart'], dtype=object),
 35: array(['Google Chrome', 'Settings', 'Gmail', 'Samsung Gallery', 'Camera',
        'Telegram', 'Google Play Store', 'Samsung Internet Browser',
        'Samsung Notes'], dtype=object),
 36: array(['Google', 'Discord', 'YouTube', 'Google Chrome', 'Facebook',
        'Instagram', 'Phone', 'Maps', 'Clock', 'Facebook Messenger',
        'Google Play Store', 'Settings', 'Spotify Music', 'Gmail',
        'Amazon Shopping', 'Google Photos', 'PayPal Mobile Cash'],
       dtype=object),
 37: array(['Phone', 'Facebook', 'Clock', 'Settings', 'Reddit', 'Gmail',
        'YouTube', 'Google Chrome', 'Google', 'Facebook Messenger',
        'Google Play Store', 'Google Photos', 'Verizon Messages',
        'Calendar', 'Walmart', 'Google Play Music', 'Google Drive'],
       dtype=object),
 38: array(['Yahoo Mail', 'Google Chrome', 'Phone', 'Hangouts', 'Gmail',
        'Google', 'Amazon Shopping', 'Messages', 'Facebook Messenger',
        'Settings', 'Google Play Store', 'Clock', 'eBay', 'Google Drive'],
       dtype=object),
 39: array(['Facebook', 'Facebook Messenger', 'Google', 'Gmail', 'Maps',
        'Settings', 'Google Chrome', 'Quora', 'Snapchat',
        'Google Play Store', 'Phone', 'Instagram', 'Google Drive',
        'Twitter', 'Amazon Shopping', 'YouTube', 'Google Photos',
        'Pandora Music', 'Messages'], dtype=object),
 40: array(['Facebook Messenger', 'Facebook', 'Twitter', 'Microsoft Outlook',
        'Google Chrome', 'Amazon Shopping', 'Google Play Store',
        'Words With Friends 2', 'Messaging', 'Google', 'Calorie Counter',
        'Android In Call UI', 'Contacts', 'Instagram', 'Spotify Music',
        'Settings'], dtype=object),
 41: array(['Google Chrome', 'Spotify Music', 'Contacts', 'YouTube',
        'Yahoo Mail', 'Samsung Gallery', 'Messages', 'Settings',
        'Calculator', 'Calendar', 'Facebook', 'Google Play Store',
        'Facebook Messenger', 'Samsung Internet Browser', 'Camera'],
       dtype=object),
 42: array(['Reddit', 'Google', 'Google Play Store', 'Settings',
        'Google Chrome', 'Messaging', 'Camera', 'Samsung Gallery',
        'Snapchat', 'Maps', 'Samsung Internet Browser'], dtype=object),
 43: array(['Messages', 'Google', 'Pinterest', 'Google Chrome',
        'Google Play Store', 'Pandora Music', 'Microsoft Outlook',
        'Settings', 'Instagram', 'Camera', 'Snapchat', 'Maps', 'Facebook',
        'Twitter', 'Samsung Gallery', 'YouTube'], dtype=object),
 44: array(['Google Chrome', 'Google Play Store', 'Settings',
        'Verizon Messages', 'Calculator', 'Calendar', 'Reddit', 'Gmail',
        'Netflix', 'Instagram', 'Maps', 'Camera', 'Samsung Gallery',
        'Robinhood', 'YouTube', 'Contacts', 'Google'], dtype=object),
 45: array(['Calendar', 'Gmail', 'Maps', 'Snapchat', 'Google', 'Reddit',
        'Google Photos', 'Google Play Store', 'Settings', 'Google Drive',
        'YouTube', 'Discord', 'Contacts'], dtype=object),
 46: array(['Facebook', 'WhatsApp Messenger', 'Messaging', 'Google Chrome',
        'Contacts', 'Android In Call UI', 'Gmail', 'Google',
        'Flipboard Briefing', 'Samsung Email', 'Camera',
        'Facebook Messenger', 'Telegram', 'YouTube', 'Samsung Gallery',
        'Twitter', 'Hangouts', 'Instagram', 'Samsung Notes', 'Settings',
        'Calculator', 'Google Play Store'], dtype=object),
 47: array(['Settings', 'Contacts', 'Android In Call UI', 'Google Play Store',
        'Google Drive', 'Gmail', 'Messaging', 'Google Chrome',
        'Google Photos', 'Facebook Messenger', 'Facebook', 'Google',
        'YouTube', 'Spotify Music'], dtype=object),
 48: array(['Instagram', 'Twitter', 'Google Chrome', 'Gmail', 'Telegram',
        'Messaging', 'WhatsApp Messenger', 'Google', 'YouTube', 'Maps',
        'Contacts', 'imo', 'Android In Call UI', 'Phone',
        'Google Play Store', 'Settings'], dtype=object),
 49: array(['Messages', 'Samsung Pay', 'Contacts', 'Google Chrome', 'Gmail',
        'Instagram', 'Calendar', 'Settings', 'Google',
        'Samsung Internet Browser', 'Facebook', 'Google Play Store',
        'Samsung Gallery', 'Spotify Music', 'Calculator', 'Google Drive'],
       dtype=object),
 50: array(['Samsung Internet Browser', 'Reward Stash', 'Calculator',
        'Settings', 'Maps', 'Camera', 'Samsung Gallery', 'Movie Play Box',
        'Google Play Store', 'Contacts', 'Google Chrome', 'YouTube',
        'Messaging', 'Pandora Music', 'Walmart', 'Facebook Messenger',
        'Google', 'Swagbucks', 'Google Drive', 'MUIQ Survey App',
        'Google Photos'], dtype=object),
 51: array(['Google', 'YouTube', 'Maps', 'Google Chrome', 'Google Play Store',
        'Settings', 'Google Play Music'], dtype=object),
 52: array(['Discord', 'Google Chrome', 'Facebook', 'Google', 'Camera',
        'Gmail', 'Facebook Messenger', 'Samsung Gallery', 'Twitter',
        'Contacts', 'Google Play Store', 'Settings', 'YouTube', 'Calendar',
        'Messages'], dtype=object),
 53: array(['Google Play Store', 'Google Chrome', 'Google', 'Google Photos',
        'Settings', 'Gmail'], dtype=object),
 54: array(['Facebook', 'Messaging', 'Google Chrome', 'Contacts',
        'Android In Call UI', 'Hangouts', 'Amazon Shopping', 'Walmart',
        'Pandora Music', 'Words With Friends 2', 'Twitter', 'Maps',
        'Google', 'Gmail', 'YouTube', 'Google Play Store', 'Settings',
        'Facebook Messenger', 'Google Drive', 'Calendar', 'Google Photos',
        'Snapchat', 'Google Play Music'], dtype=object),
 55: array(['Google', 'Samsung Internet Browser', 'Contacts', 'Gmail',
        'Ibotta', 'Microsoft Outlook', 'Samsung Pay', 'Messages',
        'Facebook', 'Google Play Music', 'Snapchat', 'Camera',
        'Samsung Gallery', 'Google Drive', 'Google Chrome',
        'Facebook Messenger', 'Settings', 'Pinterest', 'Google Play Store',
        'YouTube', 'eBay', 'PayPal Mobile Cash', 'Walmart', 'Maps'],
       dtype=object),
 56: array(['Google Chrome', 'Google', 'Gmail', 'Google Play Store',
        'Settings', 'Maps'], dtype=object),
 57: array(['Yahoo Mail', 'Google', 'Google Chrome', 'Samsung Email',
        'Contacts', 'Messages', 'Microsoft Bing Search', 'YouTube',
        'Google Play Store', 'Maps', 'Flipboard Briefing',
        'WhatsApp Messenger', 'Settings'], dtype=object),
 58: array(['S’more', 'Slidejoy', 'Google', 'Google Chrome',
        'Google Play Store', 'YouTube', 'Facebook', 'Facebook Messenger',
        'Reddit', 'Settings', 'Google Photos', 'Gmail', 'Google Drive',
        'Contacts', 'Podcast Addict', 'Phone'], dtype=object),
 59: array(['Instagram', 'Samsung Email', 'Facebook', 'Google Play Store',
        'Google', 'Verizon Messages', 'Samsung Pay', 'Google Chrome',
        'Contacts', 'Facebook Messenger', 'Camera', 'Calculator',
        'YouTube', 'Calorie Counter', 'Ibotta', 'Twitter', 'Settings'],
       dtype=object),
 60: array(['Google Play Store', 'Facebook', 'Google Chrome', 'Gmail',
        'Settings', 'Hangouts', 'Google', 'Robinhood', 'eBay', 'YouTube',
        'Twitter', 'Clean Master', 'Receipt Hog', 'Facebook Messenger',
        'MUIQ Survey App', 'Walmart', 'Contacts', 'Messaging',
        'Google Drive', 'Android In Call UI'], dtype=object),
 61: array(['Facebook Messenger', 'YouTube', 'Google Play Store', 'Google',
        'Android In Call UI', 'SurveyCow', 'Facebook', 'Yahoo Mail',
        'Google Chrome', 'Pandora Music', 'Settings', 'Camera',
        'Samsung Gallery', 'Maps', 'Contacts', 'Swagbucks',
        'Google Photos', 'MUIQ Survey App', 'Calculator', 'Messaging',
        'Receipt Hog', 'Ibotta'], dtype=object),
 62: array(['Google', 'YouTube', 'Google Chrome', 'Yahoo Mail', 'Gmail',
        'Google Play Store', 'Maps', 'Settings', 'Messages',
        'Microsoft Bing Search'], dtype=object),
 63: array(['Facebook', 'Facebook Messenger', 'Google Play Store', 'Contacts',
        'Android In Call UI', 'Messaging', 'Maps', 'Google', 'Snapchat',
        'Settings', 'Google Play Music', 'Pinterest',
        'Samsung Internet Browser', 'Calendar', 'Gmail', 'Google Photos'],
       dtype=object),
 64: array(['Google Play Store', 'Google Chrome', 'Maps', 'Facebook',
        'Messages', 'Reddit', 'Camera', 'Contacts', 'Samsung Gallery',
        'Google Drive', 'Samsung Email', 'Walmart', 'Ibotta', 'Quora',
        'Facebook Messenger', 'Settings', 'Calendar', 'Gmail',
        'Calculator', 'Lucktastic', 'YouTube', 'Google Photos',
        'Receipt Hog'], dtype=object),
 65: array(['Hulu', 'Google Play Store'], dtype=object),
 66: array(['Instagram', 'Google Chrome', 'Gmail', 'Telegram',
        'Google Play Store', 'WhatsApp Messenger', 'Spotify Music',
        'Settings', 'Google Drive', 'YouTube', 'Facebook Messenger',
        'Google', 'Maps'], dtype=object),
 67: array(['Facebook Messenger', 'Discord', 'YouTube', 'Google Chrome',
        'Google', 'Settings', 'Phone', 'Instagram', 'Netflix', 'Gmail',
        'Facebook', 'Calendar', 'Snapchat', 'Messages',
        'Google Play Store', 'Amazon Shopping', 'Google Photos',
        'MUIQ Survey App', 'Reddit', 'PayPal Mobile Cash', 'Maps',
        'Spotify Music', 'Hulu', 'Google Drive', 'Clock', 'Baseball Boy!'],
       dtype=object),
 68: array(['Google Chrome', 'Amazon Shopping', 'Google Play Store', 'Google',
        'Receipt Hog', 'Instagram', 'Facebook', 'Clock', 'Snapchat',
        'Swagbucks', 'Gmail', 'Facebook Messenger', 'YouTube', 'Maps',
        'Messages', 'Swagbucks Watch (TV)', 'Settings', 'Pinterest',
        'Yahoo Mail', 'Microsoft Outlook', 'Phone', 'WhatsApp Messenger',
        'Google Photos', 'Google Drive', 'Calendar'], dtype=object),
 69: array(['Messages', 'YouTube', 'Google Photos', 'OfferUp', 'Contacts',
        'Settings', 'Reddit', 'Google Play Store', 'Maps', 'Google Chrome',
        'Camera', 'Samsung Gallery', 'Gmail', 'Google',
        'Microsoft Outlook', 'Amazon Shopping', 'Google Play Music'],
       dtype=object),
 70: array(['Messaging', 'Contacts', 'Android In Call UI', 'Instagram',

In [40]:
# iterate through all df_start interactions and choose app_name as random app from user_to_app_dict for user_id
df_start['random_app_name'] = df_start.apply(lambda row: np.random.choice(user_to_app_dict[row['user_id']]), axis=1)
df_start.head(100)

C:\Users\Brin\AppData\Local\Temp\ipykernel_17340\1922601193.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start['random_app_name'] = df_start.apply(lambda row: np.random.choice(user_to_app_dict[row['user_id']]), axis=1)

,user_id,session_id,timestamp,app_name,event_type,time_dff,open_time,close_time,random_app_name
interaction_id,,,,,,,,,
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened,NaN,2018-01-16 06:01:05,2018-01-16 06:01:09,Google Play Store
2,0,1,2018-01-16 06:03:44,Minesweeper Classic (Mines),Opened,0 days 00:02:35,2018-01-16 06:03:44,2018-01-16 06:04:17,Google Play Store
3,0,1,2018-01-16 06:25:54,Gmail,User Interaction,0 days 00:21:37,2018-01-16 06:25:54,2018-01-16 06:25:54,Calendar
4,0,1,2018-01-16 06:26:05,Google,Opened,0 days 00:00:11,2018-01-16 06:26:05,2018-01-16 06:26:10,Amazon Shopping
5,0,1,2018-01-16 06:26:10,Instagram,Opened,0 days 00:00:00,2018-01-16 06:26:10,2018-01-16 06:26:21,Google Chrome
...,...,...,...,...,...,...,...,...,...
96,0,23,2018-01-16 22:32:56,Gmail,Closed,0 days 00:00:01,2018-01-16 22:32:56,2018-01-16 22:32:56,Google
97,0,23,2018-01-16 22:32:57,Phone,Opened,0 days 00:00:01,2018-01-16 22:32:57,2018-01-16 22:34:07,Hangouts
98,0,23,2018-01-16 22:34:07,Gmail,Opened,0 days 00:00:00,2018-01-16 22:34:07,2018-01-16 22:34:47,Amazon Shopping
99,0,23,2018-01-16 22:34:47,Google,Opened,0 days 00:00:00,2018-01-16 22:34:47,2018-01-16 22:35:22,Facebook Messenger
100,0,23,2018-01-16 22:35:22,Google Chrome,Opened,0 days 00:00:00,2018-01-16 22:35:22,2018-01-16 22:39:59,Messages

In [43]:
# create dicitonary user to accuracy
user_to_accuracy_dict = {}

# go through all interactions and check if app_name is in random_app_name for each user and save accuracy
for user_id, user_df in df_user:
    # iterate through all interactions for user_id
    accuracy = 0

    for index, row in user_df.iterrows():
        if row['app_name'] == row['random_app_name']:
            accuracy += 1

    user_to_accuracy_dict[user_id] = accuracy / len(user_df)

# print user to accuracy dictionary
user_to_accuracy_dict

{0: 0.060836501901140684,
 1: 0.06334841628959276,
 2: 0.06521739130434782,
 3: 0.08284023668639054,
 4: 0.13157894736842105,
 5: 0.03174045443897868,
 6: 0.04729082902546429,
 7: 0.043726235741444866,
 8: 0.13333333333333333,
 9: 0.046118721461187215,
 10: 0.125,
 11: 0.06609442060085836,
 12: 0.03162055335968379,
 13: 0.05153203342618384,
 14: 0.1702127659574468,
 15: 0.06201550387596899,
 16: 0.04830917874396135,
 17: 0.10493827160493827,
 18: 0.04808767613509282,
 19: 0.07471264367816093,
 20: 0.10975609756097561,
 21: 0.06164383561643835,
 22: 0.03260869565217391,
 23: 0.07058823529411765,
 24: 0.1717171717171717,
 25: 0.05437597099948213,
 26: 0.06127966356263142,
 27: 0.11194029850746269,
 28: 0.055299539170506916,
 29: 0.0914396887159533,
 30: 0.08053691275167785,
 31: 0.08647575843493054,
 32: 0.14942528735632185,
 33: 0.05409643277146217,
 34: 0.07954545454545454,
 35: 0.14285714285714285,
 36: 0.06561859193438141,
 37: 0.06218487394957983,
 38: 0.06769596199524941,
 39: 0.04265997490589712,
 40: 0.059964726631393295,
 41: 0.07228915662650602,
 42: 0.09523809523809523,
 43: 0.05975103734439834,
 44: 0.047080979284369114,
 45: 0.0959409594095941,
 46: 0.031746031746031744,
 47: 0.08450704225352113,
 48: 0.06690140845070422,
 49: 0.06237816764132553,
 50: 0.042837792075855065,
 51: 0.13513513513513514,
 52: 0.05785123966942149,
 53: 0.22727272727272727,
 54: 0.03969754253308128,
 55: 0.034013605442176874,
 56: 0.16049382716049382,
 57: 0.06694560669456066,
 58: 0.05822784810126582,
 59: 0.05196629213483146,
 60: 0.0595903165735568,
 61: 0.042380888109056554,
 62: 0.0881057268722467,
 63: 0.04892966360856269,
 64: 0.04256854256854257,
 65: 1.0,
 66: 0.06741573033707865,
 67: 0.04049416609471517,
 68: 0.0437729454956227,
 69: 0.05286343612334802,
 70: 0.10810810810810811,
 71: 0.041895784236711184,
 72: 0.06666666666666667,
 73: 0.061243144424131625,
 74: 0.03919663103336573,
 75: 0.03287671232876712,
 76: 0.0975609756097561,
 77: 0.10218978102189781,
 78: 0.08083832335329341,
 79: 0.04644194756554307,
 80: 0.07365792759051186,
 81: 0.09734513274336283,
 82: 0.061872909698996656,
 83: 0.05779334500875657,
 84: 0.06484641638225255,
 85: 0.049019607843137254,
 86: 0.18518518518518517,
 87: 0.04838709677419355,
 88: 0.07142857142857142,
 89: 0.04918032786885246,
 90: 0.08,
 91: 0.04242424242424243,
 92: 0.061224489795918366,
 93: 0.044186046511627906,
 94: 0.05678670360110803,
 95: 0.09090909090909091,
 96: 0.09420289855072464,
 97: 0.1111111111111111,
 98: 0.25,
 99: 0.05049088359046283,
 100: 0.0,
 101: 0.09259259259259259,
 102: 0.048507462686567165,
 103: 0.0787037037037037,
 104: 0.06028577020943433,
 105: 0.05764411027568922,
 106: 0.08252947481243302,
 107: 0.05708460754332314,
 108: 0.054039448797622264,
 109: 0.07667731629392971,
 110: 0.14893617021276595,
 111: 0.059805285118219746,
 112: 0.03406865568482894,
 113: 0.08333333333333333,
 114: 0.06357388316151202,
 115: 0.034693269803454434,
 116: 0.04282095931613107,
 117: 0.2857142857142857,
 118: 0.0440251572327044,
 119: 0.03764779091474798,
 120: 0.078125,
 121: 0.021406727828746176,
 122: 0.0872093023255814,
 123: 0.05555555555555555,
 124: 0.060191518467852256,
 125: 0.042042042042042045,
 126: 0.014285714285714285,
 127: 0.07086614173228346,
 128: 0.046289493019838354,
 129: 0.05479984453944812,
 130: 0.05813953488372093,
 131: 0.03948025987006497,
 132: 0.045454545454545456,
 133: 0.048038049940546966,
 134: 0.25,
 135: 0.038746908491343775,
 136: 0.05931612002791347,
 137: 0.03850440209517441,
 138: 0.03525798124366892,
 139: 0.07652210175145956,
 140: 0.05508130081300813,
 141: 0.0641025641025641,
 142: 0.0364963503649635,
 143: 0.08058608058608059,
 144: 0.04477611940298507,
 145: 0.09206349206349207,
 146: 0.043010752688172046,
 147: 0.03102878716375649,
 148: 0.05694915254237288,
 149: 0.041121495327102804,
 150: 0.05685856432125089,
 151: 0.04481675392670157,
 152: 0.06923076923076923,
 153: 0.09137055837563451,
 154: 0.04058901264866906,
 155: 0.10050251256281408,
 156: 0.0967741935483871,
 157: 0.25,
 158: 0.042242703533026116,
 159: 0.06451612903225806,
 160: 0.045741723527925195,
 161: 0.03929273084479371,
 162: 0.04284471509351892,
 163: 0.0599250936329588,
 164: 0.061946902654867256,
 165: 0.07215189873417721,
 166: 0.26865671641791045,
 167: 0.13953488372093023,
 168: 0.04498269896193772,
 169: 0.13175675675675674,
 170: 0.6,
 171: 1.0,
 172: 0.06443298969072164,
 173: 0.057754010695187166,
 174: 0.029914529914529916,
 175: 0.04216867469879518,
 176: 0.03347280334728033,
 177: 1.0,
 178: 0.06633906633906633,
 179: 0.03886138613861386,
 180: 0.03727144866385373,
 181: 0.13,
 182: 0.13385826771653545,
 183: 0.053742802303262956,
 184: 0.12903225806451613,
 185: 0.05223880597014925,
 186: 0.0574468085106383,
 187: 0.039342337052260715,
 188: 0.06543494996150885,
 189: 0.0456989247311828,
 190: 0.10283687943262411,
 191: 0.047619047619047616,
 192: 0.033183616008580816,
 193: 0.09090909090909091,
 194: 0.07553956834532374,
 195: 0.06338028169014084,
 196: 0.04854831032841504,
 197: 0.04430379746835443,
 198: 0.054161688570290724,
 199: 0.23684210526315788,
 200: 0.0546448087431694,
 201: 0.04285714285714286,
 202: 0.05627009646302251,
 203: 0.04756596060943887,
 204: 0.04085987924214033,
 205: 0.03616236162361624,
 206: 0.05255878284923928,
 207: 0.057007125890736345,
 208: 0.07446808510638298,
 209: 0.087248322147651,
 210: 0.1935483870967742,
 211: 0.0451693851944793,
 212: 0.03499469777306469,
 213: 0.06842105263157895,
 214: 0.04361370716510903,
 215: 0.06197854588796186,
 216: 0.0684931506849315,
 217: 0.058823529411764705,
 218: 0.0859375,
 219: 0.04950495049504951,
 220: 0.08695652173913043,
 221: 0.052288911495422176,
 222: 0.14049586776859505,
 223: 0.0,
 224: 0.06666666666666667,
 225: 0.0413625304136253,
 226: 0.05160807778608826,
 227: 0.05132796180244703,
 228: 0.2727272727272727,
 229: 0.037155963302752296,
 230: 0.1746031746031746,
 231: 0.04986642920747997,
 232: 1.0,
 233: 0.06481481481481481,
 234: 0.1111111111111111,
 235: 0.09090909090909091,
 236: 0.1111111111111111,
 237: 0.05405405405405406,
 238: 0.039603960396039604,
 239: 0.05531914893617021,
 240: 0.1406926406926407,
 241: 0.0654627539503386,
 242: 0.06745182012847965,
 243: 1.0,
 244: 0.058774834437086095,
 245: 0.07746478873239436,
 246: 0.05044843049327354,
 247: 0.04984740590030519,
 248: 0.04738154613466334,
 249: 0.06378132118451026,
 250: 1.0,
 251: 0.05072103431128792,
 252: 0.047253634894991924,
 253: 0.07751937984496124,
 254: 0.03770692826486818,
 255: 0.057880230518667,
 256: 0.18181818181818182,
 257: 0.04813664596273292,
 258: 0.05263157894736842,
 259: 0.03984575835475578,
 260: 0.04186834462729913,
 261: 0.058823529411764705,
 262: 0.05256183745583039,
 263: 0.05121470781352593,
 264: 0.06184935701163503,
 265: 0.06111111111111111,
 266: 0.05025125628140704,
 267: 0.03420682377769961,
 268: 0.183206106870229,
 269: 0.04973002404827805,
 270: 0.04349634353446782,
 271: 0.0330188679245283,
 272: 0.10344827586206896,
 273: 0.038898233809924306,
 274: 0.05263157894736842,
 275: 0.0636604774535809,
 276: 0.07932692307692307,
 277: 0.05411255411255411,
 278: 0.10204081632653061,
 279: 0.058922558922558925,
 280: 0.06515151515151515,
 281: 0.08129175946547884,
 282: 0.06882591093117409,
 283: 0.050401753104455806,
 284: 0.04227405247813411,
 285: 0.04467871485943775,
 286: 0.08333333333333333,
 287: 0.04452054794520548,
 288: 1.0,
 289: 0.04721311475409836,
 290: 0.03808684976112312,
 291: 0.0657439446366782}

#### Results

In [44]:
# Calculate mean and standard deviation of accuracy
mean_accuracy = np.mean(list(user_to_accuracy_dict.values()))
std_accuracy = np.std(list(user_to_accuracy_dict.values()))

mean_accuracy, std_accuracy

(0.09545466117908077, 0.15162234054750554)

### Most opened app

292

### Most recently used