In [1]:
!pip install matplotlib pandas seaborn numpy nltk

Collecting matplotlib
  Using cached matplotlib-3.8.0-cp310-cp310-win_amd64.whl.metadata (5.9 kB)
Collecting pandas
  Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl.metadata (18 kB)
Collecting seaborn
  Using cached seaborn-0.13.0-py3-none-any.whl.metadata (5.3 kB)
Collecting numpy
  Using cached numpy-1.26.1-cp310-cp310-win_amd64.whl.metadata (61 kB)
Collecting nltk
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.1.1-cp310-cp310-win_amd64.whl.metadata (5.9 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.43.1-cp310-cp310-win_amd64.whl.metadata (155 kB)
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Using cached kiwisolver-1.4.5-cp310-cp310-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (23.2)
Collecting pillow>=6.2.0 (from matplotlib)
  Using cached Pillow-10.1.0-cp310-cp310-win_amd64.whl.metadata (9.6 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting click (from nltk)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting joblib (from nltk)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting regex>=2021.8.3 (from nltk)
  Using cached regex-2023.10.3-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: six>=1.5 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: colorama in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from click->nltk) (0.4.6)
Using cached matplotlib-3.8.0-cp310-cp310-win_amd64.whl (7.6 MB)
Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl (10.7 MB)
Using cached seaborn-0.13.0-py3-none-any.whl (294 kB)
Using cached numpy-1.26.1-cp310-cp310-win_amd64.whl (15.8 MB)
Using cached contourpy-1.1.1-cp310-cp310-win_amd64.whl (477 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.43.1-cp310-cp310-win_amd64.whl (2.1 MB)
Using cached kiwisolver-1.4.5-cp310-cp310-win_amd64.whl (56 kB)
Using cached Pillow-10.1.0-cp310-cp310-win_amd64.whl (2.6 MB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Using cached regex-2023.10.3-cp310-cp310-win_amd64.whl (269 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Installing collected packages: pytz, tzdata, tqdm, regex, pyparsing, pillow, numpy, kiwisolver, joblib, fonttools, cycler, click, pandas, nltk, contourpy, matplotlib, seaborn
Successfully installed click-8.1.7 contourpy-1.1.1 cycler-0.12.1 fonttools-4.43.1 joblib-1.3.2 kiwisolver-1.4.5 matplotlib-3.8.0 nltk-3.8.1 numpy-1.26.1 pandas-2.1.1 pillow-10.1.0 pyparsing-3.1.1 pytz-2023.3.post1 regex-2023.10.3 seaborn-0.13.0 tqdm-4.66.1 tzdata-2023.3

In [2]:
%matplotlib inline

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import _pickle as cPickle
import nltk

In [3]:
df = pd.read_csv('lsapp.tsv', sep='\t', skiprows=1, header=None, names=['user_id', 'session_id', 'timestamp', 'app_name', 'event_type'])
df_open = df.loc[df['event_type'] == 'Opened']

In [4]:
df

,user_id,session_id,timestamp,app_name,event_type
0,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Closed
2,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Opened
3,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Closed
4,0,1,2018-01-16 06:01:08,Minesweeper Classic (Mines),Opened
...,...,...,...,...,...
3658584,291,76247,2018-04-06 14:35:15,Facebook,Closed
3658585,291,76247,2018-04-06 14:35:15,Facebook,Opened
3658586,291,76247,2018-04-06 14:35:37,Facebook,Closed
3658587,291,76247,2018-04-06 14:35:37,Facebook,Opened
3658588,291,76247,2018-04-06 14:35:52,Facebook Messenger,User Interaction

In [5]:
df_open.loc[:,'timestamp'] = pd.to_datetime(df_open['timestamp'])
df.loc[:,'timestamp'] = pd.to_datetime(df['timestamp'])

In [6]:
df = df.iloc[:-1, :] # last row includes only NaNs and NaT (not a number)
df

,user_id,session_id,timestamp,app_name,event_type
0,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Closed
2,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Opened
3,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Closed
4,0,1,2018-01-16 06:01:08,Minesweeper Classic (Mines),Opened
...,...,...,...,...,...
3658583,291,76247,2018-04-06 14:34:34,Facebook,Opened
3658584,291,76247,2018-04-06 14:35:15,Facebook,Closed
3658585,291,76247,2018-04-06 14:35:15,Facebook,Opened
3658586,291,76247,2018-04-06 14:35:37,Facebook,Closed
3658587,291,76247,2018-04-06 14:35:37,Facebook,Opened

In [7]:
df['time_dff']  = df[['timestamp']].diff()
df['interaction_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(1, 'm')) 
                              & (df.event_type == 'Opened')) 
                              | ~(df.app_name == df.app_name.shift(1))
                              | ~(df.user_id == df.user_id.shift(1))).cumsum()
df['session_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(5, 'm')) 
                              & (df.event_type == 'Opened')) 
                              | ~(df.user_id == df.user_id.shift(1))).cumsum()
df_start = df.drop_duplicates(subset=['interaction_id'], keep='first')
df_end = df.drop_duplicates(subset=['interaction_id'], keep='last')
df_start.set_index('interaction_id', inplace=True)
df_end.set_index('interaction_id', inplace=True)
df_start.loc[:, 'open_time'] = df_start['timestamp']
df_start.loc[:, 'close_time']  = df_end['timestamp']

C:\Users\Brin\AppData\Local\Temp\ipykernel_22644\4188201099.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time_dff']  = df[['timestamp']].diff()
C:\Users\Brin\AppData\Local\Temp\ipykernel_22644\4188201099.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['interaction_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(1, 'm'))
C:\Users\Brin\AppData\Local\Temp\ipykernel_22644\4188201099.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['session_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(5, 'm'))
C:\Users\Brin\AppData\Local\Temp\ipykernel_22644\4188201099.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start.loc[:, 'open_time'] = df_start['timestamp']
C:\Users\Brin\AppData\Local\Temp\ipykernel_22644\4188201099.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start.loc[:, 'close_time']  = df_end['timestamp']

In [8]:
df_start

,user_id,session_id,timestamp,app_name,event_type,time_dff,open_time,close_time
interaction_id,,,,,,,,
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened,NaN,2018-01-16 06:01:05,2018-01-16 06:01:09
2,0,1,2018-01-16 06:03:44,Minesweeper Classic (Mines),Opened,0 days 00:02:35,2018-01-16 06:03:44,2018-01-16 06:04:17
3,0,1,2018-01-16 06:25:54,Gmail,User Interaction,0 days 00:21:37,2018-01-16 06:25:54,2018-01-16 06:25:54
4,0,1,2018-01-16 06:26:05,Google,Opened,0 days 00:00:11,2018-01-16 06:26:05,2018-01-16 06:26:10
5,0,1,2018-01-16 06:26:10,Instagram,Opened,0 days 00:00:00,2018-01-16 06:26:10,2018-01-16 06:26:21
...,...,...,...,...,...,...,...,...
599630,291,33218,2018-04-06 12:37:57,Facebook Messenger,Opened,0 days 00:13:42,2018-04-06 12:37:57,2018-04-06 12:43:59
599631,291,33218,2018-04-06 12:47:28,Facebook Messenger,Opened,0 days 00:03:29,2018-04-06 12:47:28,2018-04-06 12:53:13
599632,291,33219,2018-04-06 13:20:12,Settings,Opened,0 days 00:26:59,2018-04-06 13:20:12,2018-04-06 13:20:14
599633,291,33220,2018-04-06 14:34:15,Settings,Opened,0 days 01:14:01,2018-04-06 14:34:15,2018-04-06 14:34:17
599634,291,33220,2018-04-06 14:34:34,Facebook,Opened,0 days 00:00:17,2018-04-06 14:34:34,2018-04-06 14:35:37